version: "3"

tasks:
  build:
    desc: Build the app
    cmds:
      - GOFLAGS=-mod=mod go build -o bin/kuby cmd/kuby/kuby.go

  run:
    desc: Run the app
    cmds:
      - GOFLAGS=-mod=mod go run cmd/kuby/kuby.go  {{.CLI_ARGS}}


  install:
    desc: Install build into machine
    cmds:
      - task: build
      - sudo cp ./bin/kuby /usr/local/bin/kuby

  uninstall:
    desc: Install build into machine
    cmds:
      - sudo rm /usr/local/bin/kuby
